name: gh-pages 

on:
  push:
    paths:
      - "docs/**"
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs-material 
          pip install mkdocs-git-revision-date-plugin
      - run: mkdocs gh-deploy --force